### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by coolcat-creations** [dgrammatiko/joomla-tools#374]
I have import { existsSync } from 'node:fs';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
npm ERR! code ELIFECYCLE

I use:
npm -v
10.7.0
node -v
v20.15.0

Am I missing something else?

Thank you!

**Comment by dgrammatiko** [comment]
Hey Elisa sorry for the late response.

Unfortunately the node log itself isn't much helpful. Could you check the version you're using? There's almost one (automated) release per day so it might be something with your current version. If not I could take a look

**Comment by coolcat-creations** [comment]
Hi @dgrammatiko , you mean the Version of joomla-tools or npm or node?

**Comment by dgrammatiko** [comment]
The version of the joomla-tools (found inside the package.json)

**Comment by coolcat-creations** [comment]
It says:
 "@dgrammatiko/joomla-tools": "^0.0.6",

**Comment by dgrammatiko** [comment]
That's a bit old could you try changing it to:

`"@dgrammatiko/joomla-tools": "^0.0.321",`

and then run `npm install`

**Comment by dgrammatiko** [comment]
Probably npm: https://www.npmjs.com/package/@dgrammatiko/joomla-tools

but tbh is better to setup something like [dependabot](https://github.com/dependabot) or [renovate](https://github.com/apps/renovate) and let the bot check/update the dependencies when needed. Another options is to remove the `node_modules` folder and run `npm install`

**Comment by coolcat-creations** [comment]
ok Thank you :)
